import { Server as HTTPServer } from 'http';
import { Server, Socket } from 'socket.io';
import jwt from 'jsonwebtoken';
import { config } from '../config';
import { logger } from '../utils/logger';
import { GameEngineFactory } from '../services/gameEngines/factory';
import { SocketJoinPayload, SocketActionPayload } from '../types';
import { prisma } from '../db';

export function initializeSocket(httpServer: HTTPServer): Server {
  const io = new Server(httpServer, {
    cors: {
      origin: config.frontendUrl,
      credentials: true,
    },
    pingTimeout: 60000,
    pingInterval: 25000,
  });

  // Authentication middleware
  io.use(async (socket, next) => {
    try {
      const token = socket.handshake.auth.token;
      
      if (!token) {
        logger.warn('Socket connection without token');
        return next(new Error('Authentication required'));
      }

      const decoded = jwt.verify(token, config.jwtSecret) as any;
      socket.data.user = {
        id: decoded.id,
        email: decoded.email,
        role: decoded.role,
      };

      next();
    } catch (error) {
      logger.error('Socket authentication failed:', error);
      next(new Error('Invalid token'));
    }
  });

  // Connection handler
  io.on('connection', (socket: Socket) => {
    const user = socket.data.user;
    logger.info(`Socket connected: ${socket.id} (user: ${user?.email})`);

    // Join session
    socket.on('join_session', async (payload: SocketJoinPayload) => {
      try {
        const { sessionId, participantId } = payload;

        // Validate session exists
        const session = await prisma.gameSession.findUnique({
          where: { id: sessionId },
          include: {
            simulation: true,
            participants: true,
          },
        });

        if (!session) {
          socket.emit('error', { message: 'Session not found' });
          return;
        }

        // Validate participant
        const participant = session.participants.find(p => p.id === participantId);
        if (!participant) {
          socket.emit('error', { message: 'Participant not found' });
          return;
        }

        // Join room
        const roomName = `session:${sessionId}`;
        await socket.join(roomName);

        logger.info(`Socket ${socket.id} joined ${roomName}`);

        // Send current state
        try {
          const engine = GameEngineFactory.create(session.simulation.slug, sessionId);
          
          // Log for debugging
          logger.info(`Creating engine for simulation: ${session.simulation.slug}, session: ${sessionId}`);
          
          const publicState = engine.getPublicState();
          const participantState = engine.getParticipantState(participantId);

          socket.emit('session_update', {
            publicState,
            participantState,
          });
        } catch (error: any) {
          // Engine might not be initialized yet
          logger.warn(`Could not get engine state for ${session.simulation.slug}:`, error?.message || error);
          socket.emit('session_update', {
            publicState: { 
              status: session.status, 
              currentRound: session.current_round,
              simulationSlug: session.simulation.slug,
              simulationName: session.simulation.name,
            },
            participantState: null,
          });
        }

        // Broadcast participant joined
        socket.to(roomName).emit('participant_joined', {
          participantId,
          playerName: participant.player_name,
          role: participant.role,
        });
      } catch (error) {
        logger.error('Join session error:', error);
        socket.emit('error', { message: 'Failed to join session' });
      }
    });

    // Helper to provide safe default config for engines (used on lazy re-init)
    const getDefaultConfig = (slug: string): any => {
      switch (slug) {
        case 'fruit-beer-game':
          return {
            leadTime: 2,
            initialInventory: 12,
            initialBackorder: 0,
            holdingCost: 0.5,
            stockoutCost: 1.0,
            numWeeks: 20,
          };
        case 'ev-gambit':
          return {
            numRounds: 5,
            startingCash: 100000000, // 100 cr
          };
        case 'hr-compensation':
          return {
            baseSalary: 500000,
            // Experts, attributes, and candidates will be generated by engine
          };
        default:
          return {};
      }
    };

    // Player action
    socket.on('player_action', async (payload: SocketActionPayload) => {
      try {
        const { sessionId, participantId, actionType, payload: actionPayload } = payload;

        // Get session
        const session = await prisma.gameSession.findUnique({
          where: { id: sessionId },
          include: { simulation: true },
        });

        if (!session) {
          socket.emit('error', { message: 'Session not found' });
          return;
        }

        if (session.status !== 'IN_PROGRESS') {
          socket.emit('error', { message: 'Session is not in progress' });
          return;
        }

        // Get engine
        const engine = GameEngineFactory.create(session.simulation.slug, sessionId);

        // Apply action, with lazy initialization if engine was not initialized
        let result;
        try {
          result = await engine.applyAction(participantId, {
            actionType,
            ...actionPayload,
          });
        } catch (error: any) {
          if (error?.message?.includes('is not initialized')) {
            logger.warn(
              `Engine not initialized for session ${sessionId}, initializing lazily before processing action`
            );
            await engine.initialize(
              (session.configuration as any) || getDefaultConfig(session.simulation.slug)
            );
            result = await engine.applyAction(participantId, {
              actionType,
              ...actionPayload,
            });
          } else {
            throw error;
          }
        }

        // Send result to player
        socket.emit('action_result', result);

        // Broadcast state update to all participants if successful
        if (result.success) {
          const roomName = `session:${sessionId}`;
          const publicState = engine.getPublicState();
          const participantState = engine.getParticipantState(participantId);
          
          io.to(roomName).emit('session_update', { 
            publicState,
            participantState: result.updatedState ? { ...participantState, ...result.updatedState } : participantState,
          });

          // Also notify facilitators about participant progress update
          // Get session to check facilitator and participant info
          const sessionForUpdate = await prisma.gameSession.findUnique({
            where: { id: sessionId },
            include: { participants: true },
          });
          
          if (sessionForUpdate?.facilitator_id) {
            // Emit to facilitator's socket if they're connected
            // This will trigger a refresh of the participants overview
            const participant = sessionForUpdate.participants.find(p => p.id === participantId);
            io.to(`session:${sessionId}`).emit('participant_progress_update', {
              participantId,
              playerName: participant?.player_name,
              updatedState: result.updatedState,
            });
          }

          // Check if all players have acted (for round advancement)
          const participants = await prisma.sessionParticipant.findMany({
            where: { session_id: sessionId, is_bot: false },
          });

          const decisions = await prisma.playerDecision.findMany({
            where: {
              session_id: sessionId,
              round_number: session.current_round + 1,
            },
          });

          if (decisions.length === participants.length) {
            logger.info(`All players acted for round ${session.current_round + 1}, advancing...`);
            
            // Advance round
            const roundResult = await engine.advanceRound();

            // Broadcast round complete
            io.to(roomName).emit('round_complete', roundResult);

            // Send updated participant states
            for (const participant of participants) {
              const participantState = engine.getParticipantState(participant.id);
              io.to(roomName).emit('participant_state_update', {
                participantId: participant.id,
                state: participantState,
              });
            }

            // Check if game is complete
            if (roundResult.isGameComplete) {
              io.to(roomName).emit('game_complete', {
                finalMetrics: await engine.computeMetrics(),
              });
            }
          }
        }
      } catch (error) {
        logger.error('Player action error:', error);
        socket.emit('error', { message: 'Failed to process action' });
      }
    });

    // Facilitator: Get participant overview
    socket.on('facilitator_get_participants', async (payload: { sessionId: string }) => {
      const { sessionId } = payload;
      let session: any = null;
      
      try {

        logger.info(`Facilitator requesting participants overview for session ${sessionId}`);

        session = await prisma.gameSession.findUnique({
          where: { id: sessionId },
          include: {
            simulation: true,
            participants: {
              include: {
                user: {
                  select: {
                    id: true,
                    email: true,
                  },
                },
              },
            },
          },
        });

        if (!session) {
          logger.error(`Session ${sessionId} not found for facilitator`);
          socket.emit('error', { message: 'Session not found' });
          return;
        }

        // Check if user is facilitator
        if (session.facilitator_id !== socket.data.user.id) {
          logger.warn(`User ${socket.data.user.id} is not facilitator for session ${sessionId}`);
          socket.emit('error', { message: 'Only facilitator can view participants' });
          return;
        }

        // Join the room if not already joined
        const roomName = `session:${sessionId}`;
        await socket.join(roomName);
        logger.info(`Facilitator socket ${socket.id} joined room ${roomName}`);

        const simulationSlug = session.simulation.slug;
        const engine = GameEngineFactory.create(simulationSlug, sessionId);
        
        // Ensure engine is initialized - check if getPublicState returns null
        try {
          const testState = engine.getPublicState();
          if (!testState) {
            logger.info(`Initializing engine for facilitator view, session ${sessionId}`);
            await engine.initialize(
              (session.configuration as any) || getDefaultConfig(simulationSlug)
            );
            logger.info(`Engine initialized successfully for facilitator view`);
          }
        } catch (initError: any) {
          logger.error(`Error initializing engine for facilitator view:`, initError);
          // Try to initialize anyway
          try {
            await engine.initialize(
              (session.configuration as any) || getDefaultConfig(simulationSlug)
            );
            logger.info(`Engine initialized on retry`);
          } catch (retryError: any) {
            logger.error(`Failed to initialize engine on retry:`, retryError);
            socket.emit('error', { message: 'Failed to initialize game engine' });
            return;
          }
        }
        
        // Get all participants' states
        // For EV Gambit, state is shared per session, but we can get participant-specific data from engine state
        const publicState = engine.getPublicState();
        logger.info(`Public state retrieved:`, { 
          hasState: !!publicState, 
          currentRound: publicState?.currentRound,
          currentEvent: publicState?.currentEvent?.title 
        });
        
        const currentRound = publicState?.currentRound ?? session.current_round ?? 0;
        const maxRounds = publicState?.maxRounds ?? session.max_rounds ?? 5;
        const currentEvent = publicState?.currentEvent || null;
        const isComplete = publicState?.isComplete || false;

        // Get all participants with their progress
        const participantsOverview = await Promise.all(
          session.participants
            .filter((p: any) => !p.is_bot) // Only human participants
            .map(async (participant: any) => {
              try {
                // Get participant-specific state from engine
                const participantState = engine.getParticipantState(participant.id);
                
                if (!participantState) {
                  logger.warn(`No state found for participant ${participant.player_name} (${participant.id})`);
                  // Return default state for this participant
                  return {
                    participantId: participant.id,
                    playerName: participant.player_name,
                    role: participant.role,
                    currentRound: 1,
                    maxRounds: maxRounds,
                    currentEvent: null,
                    status: 'waiting',
                    decisionsCount: 0,
                    quizSubmissionsCount: 0,
                    isComplete: false,
                    hasSubmittedDecision: false,
                    hasSubmittedQuiz: false,
                    scores: null,
                  };
                }
                
                logger.info(`Participant state for ${participant.player_name}:`, {
                  hasState: !!participantState,
                  decisionsCount: participantState?.decisions?.length || 0,
                  quizCount: participantState?.quizSubmissions?.length || 0,
                  currentRound: participantState?.currentRound,
                  isComplete: participantState?.isComplete
                });
                
                // Get participant-specific decisions and quiz submissions
                const decisions = participantState.decisions || [];
                const quizSubmissions = participantState.quizSubmissions || [];
                
                // Get participant-specific decisions from database
                const dbDecisions = await prisma.playerDecision.findMany({
                  where: {
                    session_id: sessionId,
                    participant_id: participant.id,
                  },
                  orderBy: {
                    round_number: 'asc',
                  },
                });

                logger.info(`DB decisions for ${participant.player_name}:`, dbDecisions.length);

                // Get participant-specific completion status and round
                const participantIsComplete = participantState?.isComplete || false;
                const participantCurrentRound = participantState?.currentRound ?? currentRound;

                // Determine status based on participant-specific progress
                let status = 'waiting';
                if (participantIsComplete) {
                  status = 'completed';
                } else if (decisions.length > 0 || quizSubmissions.length > 0 || dbDecisions.length > 0) {
                  status = 'playing';
                }

                // Use participant-specific round, but cap at maxRounds
                // currentRound is 0-indexed, so round 1 = currentRound 0, round 5 = currentRound 4
                // If complete, show maxRounds. Otherwise, show currentRound + 1, capped at maxRounds
                let displayRound = participantIsComplete 
                  ? maxRounds 
                  : Math.min(maxRounds, Math.max(1, participantCurrentRound + 1)); // Convert to 1-based and cap at maxRounds
                
                return {
                  participantId: participant.id,
                  playerName: participant.player_name,
                  role: participant.role,
                  currentRound: displayRound,
                  maxRounds: maxRounds,
                  currentEvent: participantState?.currentEvent?.title || currentEvent?.title || null,
                  status,
                  decisionsCount: Math.max(decisions.length, dbDecisions.length),
                  quizSubmissionsCount: quizSubmissions.length,
                  isComplete: participantIsComplete,
                  hasSubmittedDecision: participantState?.hasPlacedDecision || false,
                  hasSubmittedQuiz: participantState?.hasSubmittedQuiz || false,
                  scores: participantIsComplete ? (participantState?.scores || null) : null,
                };
              } catch (error: any) {
                logger.error(`Error getting state for participant ${participant.id}:`, error?.message || error);
                return {
                  participantId: participant.id,
                  playerName: participant.player_name,
                  role: participant.role,
                  currentRound: currentRound + 1,
                  maxRounds: maxRounds,
                  currentEvent: currentEvent?.title || null,
                  status: 'error',
                  decisionsCount: 0,
                  quizSubmissionsCount: 0,
                  isComplete: false,
                  hasSubmittedDecision: false,
                  hasSubmittedQuiz: false,
                  scores: null,
                };
              }
            })
        );

        logger.info(`Sending participants overview to facilitator: ${participantsOverview.length} participants`);
        logger.info(`Participants data:`, participantsOverview.map((p: any) => ({
          name: p.playerName,
          round: p.currentRound,
          status: p.status,
          decisions: p.decisionsCount,
          quizzes: p.quizSubmissionsCount
        })));
        
        socket.emit('facilitator_participants_overview', {
          sessionId,
          participants: participantsOverview,
          sessionStatus: session.status,
          currentRound: session.current_round,
        });
      } catch (error: any) {
        logger.error('Facilitator get participants error:', error);
        logger.error('Error stack:', error?.stack);
        
        // Try to get session again for error response
        let sessionStatus = 'UNKNOWN';
        let currentRound = 0;
        try {
          const errorSession = await prisma.gameSession.findUnique({
            where: { id: sessionId },
            select: { status: true, current_round: true },
          });
          if (errorSession) {
            sessionStatus = errorSession.status;
            currentRound = errorSession.current_round;
          }
        } catch (e) {
          logger.error('Failed to get session for error response:', e);
        }
        
        socket.emit('error', { 
          message: 'Failed to get participants overview',
          details: error?.message || String(error)
        });
        
        // Send empty array as fallback so UI doesn't keep spinning
        socket.emit('facilitator_participants_overview', {
          sessionId: sessionId,
          participants: [],
          sessionStatus: sessionStatus,
          currentRound: currentRound,
          error: error?.message || 'Unknown error',
        });
      }
    });

    // Facilitator control: Start round manually
    socket.on('facilitator_advance_round', async (payload: { sessionId: string }) => {
      try {
        const { sessionId } = payload;

        const session = await prisma.gameSession.findUnique({
          where: { id: sessionId },
          include: { simulation: true },
        });

        if (!session) {
          socket.emit('error', { message: 'Session not found' });
          return;
        }

        // Check if user is facilitator
        if (session.facilitator_id !== socket.data.user.id) {
          socket.emit('error', { message: 'Only facilitator can advance round' });
          return;
        }

        const engine = GameEngineFactory.create(session.simulation.slug, sessionId);
        const roundResult = await engine.advanceRound();

        const roomName = `session:${sessionId}`;
        io.to(roomName).emit('round_complete', roundResult);

        logger.info(`Round advanced by facilitator for session ${sessionId}`);
      } catch (error) {
        logger.error('Facilitator advance round error:', error);
        socket.emit('error', { message: 'Failed to advance round' });
      }
    });

    // Heartbeat
    socket.on('heartbeat', () => {
      socket.emit('heartbeat_ack', { timestamp: Date.now() });
    });

    // Disconnect
    socket.on('disconnect', (reason) => {
      logger.info(`Socket disconnected: ${socket.id} (${reason})`);
    });
  });

  logger.info('Socket.io server initialized');

  return io;
}

